#ifndef __GLOBAL__
#define __GLOBAL__

#define WIDTH_GRID 14
#define HEIGHT_GRID 14

#if GCW
#define IS_GCW 1
#define SCREEN_WIDTH 320
#define SCREEN_HEIGHT 240
#define WIDTH_GRID_PX 17
#define HEIGHT_GRID_PX 17

#define WIDTH_CONTROL_PX 30
#define HEIGHT_CONTROL_PX 30
#define SELECTED_WIDTH_CONTROL_PX 36
#define SELECTED_HEIGHT_CONTROL_PX 36
#define CONTROL_MARGIN_X 4
#define CONTROL_MARGIN_Y 4
#else
#define IS_GCW 0
#define SCREEN_WIDTH 480
#define SCREEN_HEIGHT 350
#define WIDTH_GRID_PX 25
#define HEIGHT_GRID_PX 25

#define WIDTH_CONTROL_PX 45
#define HEIGHT_CONTROL_PX 45
#define SELECTED_WIDTH_CONTROL_PX 55
#define SELECTED_HEIGHT_CONTROL_PX 55
#define CONTROL_MARGIN_X 10
#define CONTROL_MARGIN_Y 10
#endif

#define NB_COLORS 6

#define MAX_TURNS 25

#define MULTIPLAYER_PORT 1203
#define MULTIPLAYER_MIN_PLAYERS_NUMBER 2
#define MULTIPLAYER_MAX_PLAYERS_NUMBER 4

#endif
